/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [15.17KB] > D:\Gym\frontend\public\trademill1\scene-transformed.glb [332.48KB] (-2092%)
Author: e-restrepo1114 (https://sketchfab.com/EmanuelRestrepoVelez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/treadmill-proform-03e4ff99ecc24e5f8ea49d4e8df876e8
Title: treadmill ProForm
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube013_plastico_negro001_0.geometry} material={materials['plastico_negro.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube013_aluminio001_0.geometry} material={materials['aluminio.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube013_plastic_white001_0.geometry} material={materials['plastic_white.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube013_caucho_negro001_0.geometry} material={materials['caucho_negro.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube013_pasta_roja001_0.geometry} material={materials['pasta_roja.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
