/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [9.4KB] > D:\Gym\frontend\public\dumbell\scene-transformed.glb [1.13MB] (-11889%)
Author: RoutineStudio (https://sketchfab.com/TheRoutine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dumbbell-60d1d4b3fb494bfb971a920f16187b2b
Title: Dumbbell
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dumbell(props) {
  const { nodes, materials } = useGLTF('dumbell/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Dumb_Bell_Left_Weight_0.geometry} material={materials.Left_Weight} />
      <mesh geometry={nodes.Dumb_Bell_Right_Weight_0.geometry} material={materials.Right_Weight} />
      <mesh geometry={nodes.Dumb_Bell_Handle_0.geometry} material={materials.Handle} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
