/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [310.87KB] > D:\Gym\frontend\public\modulargym\scene-transformed.glb [5.26MB] (-1593%)
Author: Kristen Brown (https://sketchfab.com/kristnbrown)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modular-gym-86e8cc43d76c44e3925e625fdab155f3
Title: Modular Gym
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Modulargym(props) {
  const { nodes, materials } = useGLTF('modulargym/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.doorDoors_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
      <mesh geometry={nodes.FloorTile_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.WallspillarWall1_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.TV_Mat_TV_0.geometry} material={materials.Mat_TV} />
      <mesh geometry={nodes.Mat_Mat_Mat_0.geometry} material={materials.Mat_Mat} />
      <mesh geometry={nodes.Leg_Machine_Mat_LegMachine_0.geometry} material={materials.Mat_LegMachine} />
      <mesh geometry={nodes.Bolt15_SquatRack_0.geometry} material={materials.SquatRack} />
      <mesh geometry={nodes.treadmill1_Treadmill_lambert3SG1_0.geometry} material={materials.Treadmill_lambert3SG1} />
      <mesh geometry={nodes.Indoor_Bike_Mat_IndoorBike_0.geometry} material={materials.Mat_IndoorBike} />
      <mesh geometry={nodes.ball12_ball11_0.geometry} material={materials.ball11} />
      <mesh geometry={nodes.ball12_medrack_0.geometry} material={materials.medrack} />
      <mesh geometry={nodes.bench2_bench1_0.geometry} material={materials.bench1} />
      <mesh geometry={nodes.weightScale1_lambert2SG1_0.geometry} material={materials.lambert2SG1} />
      <mesh geometry={nodes.Weight_Bar1_WeightBar_0.geometry} material={materials.WeightBar} />
      <mesh geometry={nodes.pDisc3_papertowel_0.geometry} material={materials.papertowel} />
      <mesh geometry={nodes.Lightswitch1_Lightswich_0.geometry} material={materials.Lightswich} />
      <mesh geometry={nodes.Outlet2_Outlet1_0.geometry} material={materials.Outlet1} />
      <mesh geometry={nodes.weightrackreplacment2pCylinder55_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
