/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.65KB] > D:\Gym\frontend\public\weights\scene-transformed.glb [517.93KB] (-11038%)
Author: maddhattpatt (https://sketchfab.com/maddhatt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gym-weights-game-asset-76c7f49863384f47a6856a768c2d8d5e
Title: Gym Weights - Game Asset
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GymWeights_phong1_0.geometry} material={materials.phong1} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
