/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [41.92KB] > D:\Gym\frontend\public\idli\scene-transformed.glb [415.34KB] (-891%)
Author: AMBROSEDUDE (https://sketchfab.com/AMBROSEDUDE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/idli-south-indian-food-fe31b3ff3a734b9b918611a698ab7bd4
Title: Idli South Indian food
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001_Material002_0.geometry} material={materials['Material.002']} position={[0.103, -0.348, -0.322]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-1.707, 0.687, 0.042]} />
      <mesh geometry={nodes.Plane001_Material001_0.geometry} material={materials.PaletteMaterial001} position={[0.103, -0.348, -0.322]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-1.707, 0.687, 0.042]} />
      <mesh geometry={nodes.Plane_Material026_0.geometry} material={materials['Material.026']} position={[0.059, -0.367, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.383, 1.687, 7.084]} />
      <mesh geometry={nodes.Sphere_Material004_0.geometry} material={materials['Material.004']} position={[-0.263, -0.314, 0.481]} rotation={[1.545, 0, 0]} scale={[0.267, 0.267, 0.09]} />
      <mesh geometry={nodes.Circle001_Material006_0.geometry} material={materials['Material.006']} position={[0.028, -0.194, -0.573]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.192, 0.192, 0.154]} />
      <mesh geometry={nodes.Sphere010_Material020_0.geometry} material={materials['Material.020']} position={[0.648, -0.24, -0.629]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
