/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.28KB] > D:\Gym\frontend\public\map\scene-transformed.glb [30.68KB] (-617%)
Author: Sherbaz (https://sketchfab.com/sherlabs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-map-flag-5f5fa02e9e02420881536168a660c47b
Title: Indian Map Flag
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.indianflag} position={[0.42, 2.826, 0.333]} rotation={[1.072, 0.323, Math.PI]} scale={4.58} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
