/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.62KB] > D:\Gym\frontend\public\samosa\scene-transformed.glb [163.51KB] (-3439%)
Author: uttamg911 (https://sketchfab.com/uttamg911)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/day-226-samosa-3b8eb0e93c244747b94b354f547cd975
Title: Day 226: Samosa
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
