/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [10.64KB] > D:\Gym\frontend\public\sDumbell\scene-transformed.glb [7.66KB] (28%)
Author: Marco De Simone (https://sketchfab.com/marcodesimone888)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-dumbbell-90b161e4f6234225916e4bd08f871988
Title: Simple Dumbbell
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SmallDumbell(props) {
  const { nodes, materials } = useGLTF('sDumbell/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dumbbell_Material008_0.geometry} material={materials['Material.008']} position={[-1.7, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 0.46]} />
      <mesh geometry={nodes.dumbbell_Material009_0.geometry} material={materials['Material.009']} position={[-1.7, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 0.46]} />
      <mesh geometry={nodes.dumbbell_Material005_0.geometry} material={materials['Material.005']} position={[-1.7, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 0.46]} />
      <mesh geometry={nodes.dumbbell_Material001_0.geometry} material={materials['Material.001']} position={[-1.7, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 0.46]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
