/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [18.53KB] > D:\Gym\frontend\public\trademill2\scene-transformed.glb [523.92KB] (-2727%)
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/treadmill-machine-faed3a2a275b4fd68089e1d8bdfb7f89
Title: Treadmill Machine
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube039_treadmill_0.geometry} material={materials.treadmill} position={[0.129, 0.029, 0.023]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
