/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [32.41KB] > D:\Gym\frontend\public\thali\scene-transformed.glb [800.3KB] (-2369%)
Author: rajatnidaria (https://sketchfab.com/rajatnidaria)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-thali-free-0b8d45eb3afc4014bcc0eefbbd3a3b19
Title: Indian Thali ( FREE )
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Thali(props) {
  const { nodes, materials } = useGLTF('thali/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder1_blinn5_0.geometry} material={materials.PaletteMaterial001} position={[-0.002, 0.004, 0.05]} rotation={[0, -0.235, 0]} scale={0.002} />
      <mesh geometry={nodes.pCylinder3_blinn10_0.geometry} material={materials.PaletteMaterial002} position={[0.008, 0.002, 0.034]} scale={0.002} />
      <mesh geometry={nodes.pPlane4_blinn9_0.geometry} material={materials.PaletteMaterial003} position={[-0.009, 0.002, 0.029]} rotation={[0.607, -1.491, 1.13]} scale={0.001} />
      <mesh geometry={nodes.pPlane11_blinn4_0.geometry} material={materials.blinn4} position={[-0.049, -0.001, 0.039]} rotation={[0, 0.857, 0]} scale={[0.007, 0.009, 0.009]} />
      <mesh geometry={nodes.pPlane12_blinn2_0.geometry} material={materials.blinn2} position={[-0.048, -0.002, 0.034]} rotation={[-0.034, 0.793, 0.026]} scale={[0.007, 0.009, 0.009]} />
      <mesh geometry={nodes.pDisc1_blinn3_0.geometry} material={materials.blinn3} position={[0.018, 0, 0.04]} scale={0.014} />
      <mesh geometry={nodes.pCylinder4_blinn13_0.geometry} material={materials.PaletteMaterial004} position={[-0.002, 0.012, 0.05]} scale={0.005} />
      <mesh geometry={nodes.pCylinder5_blinn12_0.geometry} material={materials.blinn12} position={[-0.009, 0.004, 0.028]} scale={0.007} />
      <mesh geometry={nodes.pCylinder6_blinn11_0.geometry} material={materials.blinn11} position={[0.005, 0.004, 0.016]} scale={0.007} />
      <mesh geometry={nodes.pCylinder13_blinn1_0.geometry} material={materials.blinn1} position={[-0.002, 0, 0.019]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
